# Generated by Django 4.0.3 on 2022-05-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schedule_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
    ]
